### ISSUE TITLE
Expression Engine Build v2.0.2pb01 to v2.0.2pb02  error

### ISSUE THREAD

**Issue by ghost** [newism/nsm.morphine.ee_theme_addon#2]
Hi Leevi,

I’m after upgrading from Expression Engine Build v2.0.2pb01 to v2.0.2pb02 and there are problems with the Live Look plug-in. 

I think in this build they’ve taken control of the tabs that appear in the ‘Edit’ mode. You used to designate which tabs you wanted to appear within the channel settings for that particular channel. They seem to have taken out that feature in this build so that an administrator chooses which tabs he wants to appear with the Edit page itself (Open ‘side bar’ to the right and click on and off the items you want). This may have affected the ‘Live Look’ tab as this doesn’t appear any longer?

I tried to play around with your settings and could only get something to show up if I enabled ‘Module’ with the plug-in settings. When I enable ‘Module’ (which I didn’t have to do in v2.0.2pb01 – only ‘Extension’ was selected!) you get errors. I’ll just outline what I’ve done to produce the error

**Comment by leevigraham** [comment]
I'll upgrade my build today and see what happens.
